[package]
name = "data-volley-reader"
license = "MIT"
description = "A library for parsing data from the Data volley format (.dvw)."
repository = "https://github.com/Svenskithesource/data-volley-reader"
readme = "README.md"
version = "1.0.1"
edition = "2021"

[dependencies]
